# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CameraApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for CameraApp

  target 'CameraApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CameraAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'CameraApp-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for CameraApp-tvOS

  target 'CameraApp-tvOSTests' do
    inherit! :search_paths
    pod 'react-native-camera', path: '../node_modules/react-native-camera'
    # Pods for testing
  end

end
